/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat.styles` | `/chat.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/video` | `/video`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ViewProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/editprofile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownInputParams; } | { pathname: `/pages/viewpost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/writepost`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat.styles` | `/chat.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/video` | `/video`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/ViewProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/editprofile`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/viewpost`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/writepost`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat.styles${`?${string}` | `#${string}` | ''}` | `/chat.styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/video${`?${string}` | `#${string}` | ''}` | `/video${`?${string}` | `#${string}` | ''}` | `/pages/ViewProfileScreen${`?${string}` | `#${string}` | ''}` | `/pages/editprofile${`?${string}` | `#${string}` | ''}` | `/pages/signup${`?${string}` | `#${string}` | ''}` | `/pages/viewpost${`?${string}` | `#${string}` | ''}` | `/pages/writepost${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat.styles` | `/chat.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/video` | `/video`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ViewProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/editprofile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/signup`; params?: Router.UnknownInputParams; } | { pathname: `/pages/viewpost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/writepost`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
