/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/post/PostDetailScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/post/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SignUpScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ChatScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/post/PostDetailScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/post/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SignUpScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/../components/ChatScreen${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/post/PostDetailScreen.styles${`?${string}` | `#${string}` | ''}` | `/post/[id]${`?${string}` | `#${string}` | ''}` | `/../components/SignUpScreen.styles${`?${string}` | `#${string}` | ''}` | `/../components/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/../components/ui/TabBarBackground.ios${`?${string}` | `#${string}` | ''}` | `/../constants/Colors${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/post/PostDetailScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/post/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SignUpScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
